Repository wecode-bootcamp-korea/32-westagram-backend-2-team, pull requests merged in 2022-04, with the labels that each got.

#2 [제정욱] Mission 1 : Django 초기 세팅
  students/jeongwook/.gitignore
  students/jeongwook/manage.py
  students/jeongwook/requirements.txt
  students/jeongwook/westagram/__init__.py
  students/jeongwook/westagram/asgi.py
  students/jeongwook/westagram/settings.py
  students/jeongwook/westagram/urls.py
  students/jeongwook/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#1 [송재관] Mission 1 : Django 초기세팅
  students/jaekwan/.gitignore
  students/jaekwan/manage.py
  students/jaekwan/requirements.txt
  students/jaekwan/westagram/__init__.py
  students/jaekwan/westagram/asgi.py
  students/jaekwan/westagram/settings.py
  students/jaekwan/westagram/urls.py
  students/jaekwan/westagram/wsgi.py
Labels: 완료

#5 [지기성] Mission 1: Django 초기 세팅
  students/giseong/.gitignore.py
  students/giseong/giseong/__init__.py
  students/giseong/giseong/asgi.py
  students/giseong/giseong/settings.py
  students/giseong/giseong/urls.py
  students/giseong/giseong/wsgi.py
  students/giseong/manage.py
  students/giseong/requirements.txt
Labels: 멘토 리뷰 요청

#6 [박현지] Mission 1 : Django 초기 세팅
  students/hyunji/.gitignore
  students/hyunji/manage.py
  students/hyunji/requirements.txt
  students/hyunji/westagram/__init__.py
  students/hyunji/westagram/asgi.py
  students/hyunji/westagram/settings.py
  students/hyunji/westagram/urls.py
  students/hyunji/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#3 [제정욱] Mission 2: 모델링
  students/jeongwook/users/__init__.py
  students/jeongwook/users/admin.py
  students/jeongwook/users/apps.py
  students/jeongwook/users/migrations/__init__.py
  students/jeongwook/users/models.py
  students/jeongwook/users/tests.py
  students/jeongwook/users/views.py
  students/jeongwook/westagram/settings.py
Labels: 멘토 리뷰 요청

#4 [송재관] Mission 2: 모델링
  students/jaekwan/users/__init__.py
  students/jaekwan/users/admin.py
  students/jaekwan/users/apps.py
  students/jaekwan/users/migrations/__init__.py
  students/jaekwan/users/models.py
  students/jaekwan/users/tests.py
  students/jaekwan/users/views.py
  students/jaekwan/westagram/settings.py
Labels: 멘토 리뷰 요청

#8 [박현지] Mission 2: 모델링
  students/hyunji/users/__init__.py
  students/hyunji/users/admin.py
  students/hyunji/users/apps.py
  students/hyunji/users/migrations/__init__.py
  students/hyunji/users/models.py
  students/hyunji/users/tests.py
  students/hyunji/users/views.py
Labels: 멘토 리뷰 요청

#10 [송재관] Mission 2: 모델링
  students/jaekwan/users/migrations/0001_initial.py
Labels: 멘토 리뷰 요청

#9 [지기성] Mission 2 모델링 수정#1
  students/giseong/.gitignore
  students/giseong/giseong/settings.py
  students/giseong/users/__init__.py
  students/giseong/users/admin.py
  students/giseong/users/apps.py
  students/giseong/users/migrations/0001_initial.py
  students/giseong/users/migrations/__init__.py
  students/giseong/users/models.py
  students/giseong/users/tests.py
  students/giseong/users/views.py
Labels: 멘토 리뷰 요청

#12 [송재관] Mission 3: 회원가입 기능 구현
  students/jaekwan/users/urls.py
  students/jaekwan/users/views.py
  students/jaekwan/westagram/urls.py
Labels: 멘토 리뷰 요청

#14 [박현지] Mission 3: 회원가입 기능 구현
  students/hyunji/users/migrations/0001_initial.py
  students/hyunji/users/urls.py
  students/hyunji/users/views.py
  students/hyunji/westagram/settings.py
  students/hyunji/westagram/urls.py
Labels: 멘토 리뷰 요청

#15 [지기성] Mission 3: 회원가입 기능 구현
  students/giseong/giseong/settings.py
  students/giseong/giseong/urls.py
  students/giseong/users/models.py
  students/giseong/users/urls.py
  students/giseong/users/validators.py
  students/giseong/users/views.py
Labels: 멘토 리뷰 요청

#11 [제정욱] Mission 3: 회원가입 기능 구현
  students/jeongwook/users/migrations/0001_initial.py
  students/jeongwook/users/urls.py
  students/jeongwook/users/validation.py
  students/jeongwook/users/views.py
  students/jeongwook/westagram/urls.py
Labels: 멘토 리뷰 요청

#16 [제정욱] Mission 4: 로그인 기능 구현
  students/jeongwook/users/urls.py
  students/jeongwook/users/validation.py
  students/jeongwook/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#17 [지기성] Mission 4: 로그인 기능 구현
  students/giseong/users/urls.py
  students/giseong/users/validators.py
  students/giseong/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#19 [송재관] Mission 4: 로그인 기능 구현
  students/jaekwan/users/urls.py
  students/jaekwan/users/validation.py
  students/jaekwan/users/views.py
Labels: 피어 리뷰 완료

#20 [제정욱] Mission 5: 회원가입 비밀번호 암호화 적용
  students/jeongwook/requirements.txt
  students/jeongwook/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 요청

#24 [박현지] Mission 5: 회원가입 비밀번호 암호화 적용
  students/hyunji/requirements.txt
  students/hyunji/users/urls.py
  students/hyunji/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 요청

#23 [송재관] Mission 5: 회원가입 비밀번호 암호화 적용
  students/jaekwan/requirements.txt
  students/jaekwan/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 요청
